name: 'Build release'

on:
  push:
    branches:
      - master
jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: 'Push to JSON repo'
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_folder: 'dist'
          destination_repo: 'vikyd/vue-monaco-singleline-custom-language'
          destination_branch: 'dist'
          commit_msg: 'feat: update demo'